"""Serving a screenshot or a screen recording back.

**These render inline, and `routes/artifacts.py` forces a download. The
difference is deliberate and worth stating, because the rule there is a security
property, not a style choice.** An artifact's CONTENT is whatever a model wrote —
an `.svg` or `.html` it authored can carry script, so it must never render in
this app's origin. A capture's content is pixels the operating system produced;
no model wrote a byte of it, and showing a screenshot is the entire point of
taking one.

The parts a model COULD influence are removed rather than trusted: the id is
generated by `captures.py` and matched against a fixed shape, the filename never
comes from a tool argument, and the type served is fixed per kind rather than
sniffed from the file. `nosniff` and a sandboxing CSP stay, so a file that
somehow was not what we think it is still cannot execute.
"""

from __future__ import annotations

from fastapi import APIRouter
from fastapi.responses import FileResponse, JSONResponse

from ..control.captures import KINDS, RECORDING, SCREENSHOT, clear, get, recent

router = APIRouter(prefix="/api")

_NOT_FOUND = {"ok": False, "error": "Not found."}


@router.get("/captures/{kind}")
def list_captures(kind: str) -> JSONResponse:
    known = KINDS.get(kind)
    if known is None:
        return JSONResponse(_NOT_FOUND, status_code=404)
    return JSONResponse({"captures": [c.as_dict() for c in recent(known)]})


@router.get("/captures/{kind}/{capture_id}")
def serve(kind: str, capture_id: str):
    capture = get(kind, capture_id)
    if capture is None:
        return JSONResponse(_NOT_FOUND, status_code=404)
    known = KINDS[kind]
    return FileResponse(
        capture.path,
        media_type=known.mime_type,
        headers={
            # Inline, unlike an artifact — see the module docstring for why that
            # is safe here and not there.
            "Content-Disposition": f'inline; filename="{capture.id}{known.suffix}"',
            "X-Content-Type-Options": "nosniff",
            "Content-Security-Policy": "default-src 'none'; sandbox",
            # A capture is a moment, not a document: a stale one is misleading.
            "Cache-Control": "no-store",
        },
    )


@router.delete("/captures/{kind}")
def clear_captures(kind: str) -> JSONResponse:
    known = KINDS.get(kind)
    if known is None:
        return JSONResponse(_NOT_FOUND, status_code=404)
    return JSONResponse({"ok": True, "removed": clear(known)})


__all__ = ["router", "SCREENSHOT", "RECORDING"]
